name: Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Run a script
      run: echo "This job is running on a self-hosted runner!"
